apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"mysql-persistent-init"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"4Gi"},"hostPath":{"path":"/etc/pe-db-data/mysql"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"manual","volumeMode":"Filesystem"}}
  creationTimestamp: "2021-02-07T00:00:40Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: k3s
    operation: Update
    time: "2021-02-07T00:00:40Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:type: {}
      f:spec:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:hostPath:
          .: {}
          f:path: {}
          f:type: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-02-07T00:00:40Z"
  name: mysql-persistent-init
  resourceVersion: "4482"
  uid: 95feb47e-424e-46ff-8006-7dbf36422e70
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /etc/pe-db-data/mysql/init
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Available
