# apiVersion: v1
# kind: Namespace
# metadata:
#   name: default
#   labels:
#     name: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: svc-ecr-renew-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cr-ecr-renew-demo
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: []
    verbs: ["get","delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: rb-ecr-renew-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cr-ecr-renew-demo
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew-demo
    namespace: default
